version: "3"

services:
  ubuntu:
    image: zhonger/ubuntu:advance-noble
    container_name: dev
    stdin_open: true
    tty: true
    volumes:
     - /etc/localtime:/etc/localtime
    restart: always